apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.backendhello.name }}
spec:
  selector:
    app: {{ .Values.services.backendhello.workloadLabel }}
  ports:
    - port: {{ .Values.services.backendhello.port }}
      nodePort: {{ .Values.services.backendhello.nodePort }}
  type: {{ .Values.services.backendhello.type }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.backendprofile.name }}
spec:
  selector:
    app: {{ .Values.services.backendprofile.workloadLabel }}
  ports:
    - port: {{ .Values.services.backendprofile.port }}
      nodePort: {{ .Values.services.backendprofile.nodePort }}
  type: {{ .Values.services.backendprofile.type }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.frontend.name }}
spec:
  selector:
    app: {{ .Values.services.frontend.workloadLabel }}
  ports:
    - port: {{ .Values.services.frontend.port }}
      targetPort: {{ .Values.services.frontend.targetPort }}
  type: {{ .Values.services.frontend.type }}