apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.workloads.backendhello.name }}
  labels:
    app: {{ .Values.workloads.backendhello.label }}
spec:
  replicas: {{ .Values.workloads.backendhello.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.workloads.backendhello.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.workloads.backendhello.label }}
    spec:
      containers:
        - name: {{ .Values.workloads.backendhello.containerName }}
          image: {{ .Values.workloads.backendhello.image }}
          ports:
            - containerPort: {{ .Values.workloads.backendhello.port }}
              name: {{ .Values.workloads.backendhello.portName }}
          imagePullPolicy: {{ .Values.workloads.backendhello.pullPolicy }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.workloads.backendprofile.name }}
  labels:
    app: {{ .Values.workloads.backendprofile.label }}
spec:
  replicas: {{ .Values.workloads.backendprofile.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.workloads.backendprofile.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.workloads.backendprofile.label }}
    spec:
      containers:
        - name: {{ .Values.workloads.backendprofile.containerName }}
          image: {{ .Values.workloads.backendprofile.image }}
          ports:
            - containerPort: {{ .Values.workloads.backendprofile.port }}
              name: {{ .Values.workloads.backendprofile.portName }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.workloads.frontend.name }}
  labels:
    app: {{ .Values.workloads.frontend.label }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.workloads.frontend.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.workloads.frontend.label }}
    spec:
      containers:
        - name: {{ .Values.workloads.frontend.containerName }}
          image: {{ .Values.workloads.frontend.image }}
          ports:
            - containerPort: {{ .Values.workloads.frontend.port }}
              name: {{ .Values.workloads.frontend.portName }}
          imagePullPolicy: {{ .Values.workloads.frontend.pullPolicy }}