apiVersion: v1
kind: Service
metadata:
  name: backend-hello
spec:
  selector:
    app: backend-hello
  ports:
    - port: 4200
      name: hello
      nodePort: 30010
  type: NodePort
  
---

apiVersion: v1
kind: Service
metadata:
  name: backend-profile
spec:
  selector:
    app: backend-profile
  ports:
    - port: 4400
      name: profile
      nodePort: 30020
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      name: frontend
      targetPort: 3000
  type: LoadBalancer