apiVersion: v1
kind: Service
metadata:
  name: backend-hello
spec:
  selector:
    app: backend-hello
  ports:
    - port: 4200
      name: hello
      targetPort: 4200
  type: ClusterIP
  
---

apiVersion: v1
kind: Service
metadata:
  name: backend-profile
spec:
  selector:
    app: backend-profile
  ports:
    - port: 4400
      name: profile
      targetPort: 4400
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      name: frontend
      targetPort: 3000
  type: LoadBalancer