apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-hello
  labels:
    app: backend-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-hello
  template:
    metadata:
      labels:
        app: backend-hello
    spec:
      containers:
        - name: backend-hello
          image: 367065853931.dkr.ecr.ap-south-1.amazonaws.com/microservice-backend-hello:latest
          ports:
            - containerPort: 4200
              name: hello-port

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-profile
  labels:
    app: backend-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-profile
  template:
    metadata:
      labels:
        app: backend-profile
    spec:
      containers:
        - name: backend-profile
          image: 367065853931.dkr.ecr.ap-south-1.amazonaws.com/microservice-backend-profile:latest
          ports:
            - containerPort: 4400
              name: profile-port

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 367065853931.dkr.ecr.ap-south-1.amazonaws.com/microservice-frontend:latest
          ports:
            - containerPort: 3000
              name: frontend-port