workloads:
  backendhello:
    name: backend-hello
    label: backend-hello
    replicas: 1
    image: narsss1234/microservice-backend-hello:latest
    containerName: backend-hello
    port: 4200
    portName: hello-port
    pullPolicy: IfNotPresent

  backendprofile:
    name: backend-profile
    label: backend-profile
    replicas: 1
    image: narsss1234/microservice-backend-profile:latest
    containerName: backend-profile
    port: 4400
    portName: profile-port
    pullPolicy: IfNotPresent

  frontend:
    name: frontend
    label: frontend
    replicas: 1
    image: narsss1234/microservice-frontend:latest
    containerName: frontend
    portName: frontend-port
    port: 3000
    pullPolicy: Always

services:
  backendhello:
    name: backend-hello
    workloadLabel: backend-hello
    port: 4200
    nodePort: 30010
    type: NodePort

  backendprofile:
    name: backend-profile
    workloadLabel: backend-profile
    port: 4400
    nodePort: 30020
    type: NodePort
  
  frontend:
    name: frontend
    workloadLabel: frontend
    port: 3000
    targetPort: 3000
    type: LoadBalancer